### ISSUE TITLE
Crash: Error loading class

### ISSUE THREAD

**Issue by Zesheir** [LlamaLad7/MixinExtras#100]
Sorry for asking about an issue which is probably fairly simple, but I'm somewhat new to modding/mixins. I'm using Wrapoperation to mixin the entity class, which currently functions fine in the dev environment, but crashes when I build and attempt to use the jar, giving me a `Error loading class: com/llamalad7/mixinextras/injector/wrapoperation/Operation (java.lang.ClassNotFoundException: com.llamalad7.mixinextras.injector.wrapoperation.Operation)` error. I looked through some previous issues that were similar and tried building the jar using the jarjar task - but this resulted in a far longer, more complicated crash: https://pastebin.com/L5xpTLbN. No idea what is going on here or why using the jarjar task seems to essentially break most of my registry objects? I can share the repository this is on if necessary, I'm assuming/hoping I've just done something simple wrong, but if anyone can point me in the right direction that would be immensely helpful. This is on 1.20.1 Forge, if that's unclear from the crash report.

**Comment by LlamaLad7** [comment]
You need to run the normal build task but use the -all jar from the build outputs.

**Comment by Zesheir** [comment]
The normal build task doesn't seem to generate a -all jar, that only appears through the 'jarjar' task, and using that jar causes the crash that was linked. Unless I'm supposed to be looking in a different folder than libs for the outputs I'm not sure what I'm missing.

**Comment by LlamaLad7** [comment]
Please provide a reproduction repo

**Comment by Zesheir** [comment]
Nevermind, figured it out, I just misunderstood what you were meaning. Up until this point I hadn't been using the actual build task to generate the jar, just the jar task, build creates a proper -all jar and that runs fine. Sorry for the trouble!
