### ISSUE TITLE
Support for JarJar

### ISSUE THREAD

**Issue by Ran-helo** [LlamaLad7/MixinExtras#12]
MixinExtras doesn't have a mods.toml
so Forge's JarJar no work

**Comment by Ran-helo** [comment]
Oh wait I just realized that the project doesn't contain the `fabric.mod.json` an that Fabric generates the `fabric.mod.json`
Seems like more of a [JarJar](https://github.com/MinecraftForge/JarJar) issue then

Well for now I guess I am going to make a custom plugin which auto generates the `mods.toml` and probably PR that onto Forge

**Comment by MaxNeedsSnacks** [comment]
For people coming across this issue later down the line, this is being tracked at https://github.com/architectury/architectury-loom/issues/96
