### ISSUE TITLE
Refmap not working

### ISSUE THREAD

**Issue by tox1cozZ** [LlamaLad7/MixinExtras#13]
Automatic generation of refmap during build does not work with MixinExtras annotations

**Comment by LlamaLad7** [comment]
Did you register its annotation processor?

**Comment by tox1cozZ** [comment]
Yes. I ported mixins to 1.7.10 and added your annotations.
I made a dependency for them with the annotation processor and connected it via annotationProcessor.
But it didn't work... I thought that I did something wrong and decided to check on the MixinBooter 1.12.2, but the refmap for your annotations is also not generated there.

**Comment by LlamaLad7** [comment]
If it doesn't work on mixinbooter then that's almost certainly their issue, so talk to them about it. They decided just to copy the code and remove stuff instead of bundling it, and the refmap generates just fine on 1.12.2 when setting up mixin manually.

**Comment by tox1cozZ** [comment]
Okay, sorry.
Yes, you are right, everything works.
