### ISSUE TITLE
Localcapture for @ModifyExpressionValue

### ISSUE THREAD

**Issue by KingContaria** [LlamaLad7/MixinExtras#17]
Hi,
since its possible to get the enclosing methods parameters, i was wondering if you'd consider also adding localcapture to `@ModifyExpressionValue`?

**Comment by LlamaLad7** [comment]
Did you have a specific use-case in mind for this? I don't currently have any plans to add it because it would add an awful lot of complexity for me and I'm a firm believer that it's never the best way to do things.

**Comment by KingContaria** [comment]
![image](https://user-images.githubusercontent.com/98704937/202140756-a751843b-9ada-4e7a-89a8-df4a1188a9de.png)
I am trying to use ModifyExpressionValue to transform
`boolean bl = blockHitResult.getBlockPos().equals(blockPos);`
to
`boolean bl = blockHitResult.getBlockPos().equals(blockPos) && blockHitResult.getType() != HitResult.Type.MISS;`
and capturing the blockHitResult seemed like the cleanest way to do that.
I know could do some obscure solutions like modifying the getBlockPos instead to return some blockpos thats never equal to `blockPos` but it seems like a less readable/straight forward solution
if you don't want to add localcapture tho i can resort to that so it wouldn't be too big a deal, i just liked it because of the readability mainly
what exactly is so bad about localcapture anyway i never really understood?

**Comment by KingContaria** [comment]
This should be covered by sugar, correct?

**Comment by LlamaLad7** [comment]
Yep, was just about to comment that lol

**Comment by KingContaria** [comment]
working very nicely! :)

![image](https://user-images.githubusercontent.com/98704937/211633587-f3153b89-383d-4425-9e48-bf73fe63814e.png)
