### ISSUE TITLE
JiJ-able fabric mod version

### ISSUE THREAD

**Issue by altrisi** [LlamaLad7/MixinExtras#2]
Hi!

Amazing library first of all, looks really useful!

Do you think it'd be a good idea to have a JiJ-able fabric mod (maybe as a sub project/module so the main code doesn't depend on it) so if other mods can directly JiJ it, there's no need to load the same library multiple times in different locations (via shadow) and the initialization is also handled by it? That'd also make it more easily version-able and have a proper entry as a mod.

Just a suggestion that crossed my mind, what do you think?

**Comment by LlamaLad7** [comment]
You can already JiJ it on fabric. Simply add `include` around it in your build script and loom will generate a dummy `fabric.mod.json` for it.

**Comment by altrisi** [comment]
Yeah ik it works, just wanted to suggest an official one so it's consistent across mods, can have extra metadata, and handle initialization by itself if wanted too.

**Comment by LlamaLad7** [comment]
Personally I'm not sure I see the benefits as outweighing the desire not to have platform-specific code. If I do ever need to store extra metadata, chances are it wouldn't be fabric-specific anyway, so I'd still need my own system to do so. The only real benefit would be not having to initialize it yourself, but to be honest I don't think that's enough of a pain to warrant publishing lots of version-specific artifacts.

**Comment by altrisi** [comment]
I'll close the issue then

**Comment by LlamaLad7** [comment]
Kind of changed my mind so there's a fabric-specific artifact as of `0.2.0-beta.5`
