### ISSUE TITLE
Docs in javadocs?

### ISSUE THREAD

**Issue by MattiDragon** [LlamaLad7/MixinExtras#20]
It's kind of annoying to have to open up this github page whenever I want to check the syntax of one of your injectors. Copying the docs or at least the most important parts into javadocs would make usage a lot smoother.

**Comment by LlamaLad7** [comment]
Linking might be a shout, i’m not that keen on needing to do a new release every time i want to update the docs.

**Comment by Earthcomputer** [comment]
I also think this is more important now that MixinExtras will be shipped with Fabric.

**Comment by LlamaLad7** [comment]
Done in 0.3.1
