### ISSUE TITLE
Incompatible with a lot of mods [1.19.2]

### ISSUE THREAD

**Issue by itsdinkd** [LlamaLad7/MixinExtras#28]
Well, a mod i used in my modpack AQM2 updated its use of MixinExtras to use 0.2.0-beta6 instead of beta2.  After updating MCDW,, I can no longer launch the pack, due to MixinExtras.

https://gist.github.com/itsdinkd/4911ab3ea231038079b3a34f6ff04e1c

**Comment by LlamaLad7** [comment]
Can you give reproduction instructions?

**Comment by itsdinkd** [comment]
1. Launch the modpack.

**Comment by LlamaLad7** [comment]
They're depending on it wrong. See https://github.com/chronosacaria/MCDungeonsWeapons/pull/216.
