### ISSUE TITLE
[Request] Include binaries in github releases

### ISSUE THREAD

**Issue by Gamebuster19901** [LlamaLad7/MixinExtras#3]
Can you include the built binaries in the github releases? I don't use Jitpack because of https://github.com/jitpack/jitpack.io/issues/3973. 

I also need to download the dependencies at runtime, and I've set up a system for myself to do download artifacts from github releases.

**Comment by LlamaLad7** [comment]
Sure. I've updated the 0.0.2 release with a binary and will provide them for future releases as well.
