### ISSUE TITLE
Massive lag caused by MixinExtras

### ISSUE THREAD

**Issue by marlester-dev** [LlamaLad7/MixinExtras#32]
So I was experiencing massive lag and I run spark profiler to find out what was causing the lag and I saw this:
![lag](https://github.com/LlamaLad7/MixinExtras/assets/77095872/b7e19175-146f-4e6d-8b65-4b35d82fa0bc)
the mod is not even in my mods folder but still eating the most server thread, I am running Better MC fabric modpack,

**Comment by LlamaLad7** [comment]
Update spark. The lag is nothing to do with mixinextras, it's just blamed for random stuff. I fixed the bug here https://github.com/lucko/spark/pull/330
