### ISSUE TITLE
Broken Refmaps in beta

### ISSUE THREAD

**Issue by mattymatty97** [LlamaLad7/MixinExtras#34]
Since https://github.com/LlamaLad7/MixinExtras/releases/tag/0.2.0-beta.5 fabric refmaps seems to be broken, all the entries from MixinExtras annotations are not added to the refmap causing a crash if loaded outside of dev environment

**Comment by LlamaLad7** [comment]
You're gonna need to provide a lot more detail because I am certain that is not the case if it's set up properly.

**Comment by mattymatty97** [comment]
btw i'm loving the work you've done on this it allows making mod compatibility so much easier

**Comment by LlamaLad7** [comment]
I assume it's because you didn't follow the new readme which is linked in the release notes https://gist.github.com/LlamaLad7/ec597b6d02d39b8a2e35559f9fcce42f

**Comment by mattymatty97** [comment]
i did try using the include(implementation(... but the output was the same
i use the provided which basically merges include(implementation(

am i still missing something from the new README?

**Comment by LlamaLad7** [comment]
You're missing the fact that the dependency has completely changed.
```
com.github.llamalad7.mixinextras:mixinextras-fabric:0.2.0-beta.8
```

**Comment by mattymatty97** [comment]
oh... yeah i completely missed that... errr... let me test it and close the issue 😅

**Comment by LlamaLad7** [comment]
It doesn't require a login afaik

**Comment by mattymatty97** [comment]
![image](https://github.com/LlamaLad7/MixinExtras/assets/33039934/54338114-de6a-46b7-a90b-2e79922495e9)
![image](https://github.com/LlamaLad7/MixinExtras/assets/33039934/433567b9-c887-401b-b1e3-ae05d87c78d1)

**Comment by mattymatty97** [comment]
ok nevermind.... it worked now 🤷

**Comment by Gamebuster19901** [comment]
> ok now jitpack.io requires a login for that repository which i guess is intended and restricted so i guess i'll stay on beta.4 until you do a release, thanks for your help

Just a note, if this repository published artifacts to `MavenLocal()`, users could use [gradle source dependencies](https://blog.gradle.org/introducing-source-dependencies) instead of relying on Jitpack which is known to just stop working and break builds randomly.

Gradle would `git clone` the repo and build it. Then use the built binary for the project.
