### ISSUE TITLE
add initializing string to mod

### ISSUE THREAD

**Issue by swapmasterx** [LlamaLad7/MixinExtras#38]
New to modding so apologies if its an obvious one. How and where do I put the "MixinExtrasBootstrap.init();" string? The tutorial doesn't say where the file to place it in is at or how it goes in

**Comment by swapmasterx** [comment]
I've just been having a hair pulling time getting all the dependencies working and I've just reached a point where I am at loss on what to do. 
MC version 1.19.2

[build.gradle.txt](https://github.com/LlamaLad7/MixinExtras/files/12268913/build.gradle.txt) Gradle build 
[error.txt](https://github.com/LlamaLad7/MixinExtras/files/12268914/error.txt) Error log from launching current build

**Comment by LlamaLad7** [comment]
As mentioned in the README you need to initialize it in a preLaunch entrypoint. The easiest way to do that is by a method reference:
```json
"preLaunch": ["com.llamalad7.mixinextras.MixinExtrasBootstrap::init"]
```
in the entrypoints block of your fabric mod json. The docs could probably be clearer but in the next release you won't need to initialize it yourself anyway.

**Comment by swapmasterx** [comment]
Now I'm confused because that's what I tried before and I still got a crash even when putting it in all three fabric.mod.json's.

**Comment by LlamaLad7** [comment]
Show the crash then

**Comment by swapmasterx** [comment]
Sorry for the wait, a Java process sometimes keeps mapping.jar open preventing Gradle from compiling so I have to dance with task manager some to fix it.
[error.txt](https://github.com/LlamaLad7/MixinExtras/files/12270414/error.txt)

**Comment by LlamaLad7** [comment]
That's unrelated to MixinExtras and is caused by you having multiple versions of fabric-loader on the classpath. See [this message from the fabric discord](https://canary.discord.com/channels/507304429255393322/842691768175951942/1093276385742696488).

**Comment by swapmasterx** [comment]
Ok fingers crossed this works.

**Comment by swapmasterx** [comment]
IT FINALLY WORKS!!!! Thank you so much!!!! I CAN FINALLY MOD! :D
