### ISSUE TITLE
[Suggestion] Wrap multiple lines with condition

### ISSUE THREAD

**Issue by glowredman** [LlamaLad7/MixinExtras#39]
Wraping a code block with an if-statement is fairly easy with ASM, for example:
```java
    private static class MVrenderHand extends MethodVisitor {

        private Label label;

        public MVrenderHand(MethodVisitor mv) {
            super(Opcodes.ASM4, mv);
            label = new Label();
        }

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String desc) {
            // Wraps the code from GL11.glPushMatrix() to GL11.glPopMatrix() in an if(!Shaders.isHandRendered) check
            if (Names.equals("org/lwjgl/opengl/GL11", "glPushMatrix", "()V", owner, name, desc)) {
                mv.visitFieldInsn(
                        Opcodes.GETSTATIC,
                        "com/gtnewhorizons/angelica/client/Shaders",
                        "isHandRendered",
                        "Z");
                mv.visitJumpInsn(Opcodes.IFNE, label);
                mv.visitMethodInsn(opcode, owner, name, desc);
                return;
            } else if (Names.equals("org/lwjgl/opengl/GL11", "glPopMatrix", "()V", owner, name, desc)) {
                mv.visitMethodInsn(opcode, owner, name, desc);
                mv.visitLabel(label);
                mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
                return;
            }
            mv.visitMethodInsn(opcode, owner, name, desc);
        }
    }
```
It would be nice, if either `@WrapWithCondition` would be expanded to allow this or a seperate annotation would be implemented.

**Comment by fxmorin** [comment]
On that note. Ive already written a Mixin plugin that can do this, however due to how many conflicts and issues it would cause, I never released it.
![image](https://github.com/LlamaLad7/MixinExtras/assets/28154542/bedeffa6-8770-4c29-bfd6-32fcb16a4210)
![image](https://github.com/LlamaLad7/MixinExtras/assets/28154542/7ae5594e-385f-4a41-9764-3a274d5ce841)

**Comment by Papierkorb2292** [comment]
@fxmorin 
In your first example, you can for example also use `@ModifyConstant` or `@ModifyArg(s)` to apply your changes. Also, the second mixin seems to wrap the same section as the first.
In general though, always returning `false` when wrapping something with a condition, should be avoided. If something is supposed to never be executed, a `@Redirect` can be used.
Maybe another injector could be created, which removes a section of code and still checks, whether it conflicts with other mods.

Such injectors however, would require a lot of bytecode validation to make sure that the section can actually be wrapped with a condition. For example, it needs to check whether all necessary variables are initialized, along with maybe adding another injector, which would be able to initialize these variables. It would also need to check, whether no necessary `return` or `throw` statements were wrapped. Overlapping with other such injectors and control flow present in the target method might also need to be handled. All of which, on a bytecode level, is not easy.

**Comment by LlamaLad7** [comment]
Yeah this is simply not feasible to do in a general way. The stack needs to be equal at the start and the end which makes targeting the bounds a huge pain, you have the possibility of overlapping sections, your wrapping might lead to execution falling through, etc. Moreover, there should never be a situation in which you can't achieve your goals with other injectors. At the very worst you may need to use many `@WrapWithCondition`s and a `@Share`d flag, but generally you can do something cleaner e.g. by hijacking an existing check. If you have a specific situation you want this for, ask in the mixin discord about how to do it with existing tools. It's always possible.
