### ISSUE TITLE
[Request] Be able to get a reference to the caller of non static methods in ModifyExpressionValue

### ISSUE THREAD

**Issue by ShaksterNano** [LlamaLad7/MixinExtras#4]
If targeting a non static method call with ModifyExpressionValue, it would be great if it was possible to get a reference to the object the method being called belongs to, similar to Redirect. A reference to the method arguments would also be nice if that is possible.

**Comment by LlamaLad7** [comment]
This wouldn't be hugely straightforward given being able to capture the *enclosing* method's args (straight after the expression result) is already locked into the API. I'll definitely look into it though.

**Comment by LlamaLad7** [comment]
https://github.com/LlamaLad7/MixinExtras/wiki/WrapOperation should cover this use-case now.

**Comment by LlamaLad7** [comment]
And it's now stable, which I think marks the completion of this goal.
