### ISSUE TITLE
Mixin keeps crashing and prompting to disable mods

### ISSUE THREAD

**Issue by MC-Boy1122** [LlamaLad7/MixinExtras#43]
https://mclo.gs/FjYjhYs

it keeps crashing, and i had to delete about 7 mods before this log
is there a solution that i can play pls

**Comment by LlamaLad7** [comment]
That's an issue with the now abandoned Debugify. As a workaround open it in something like 7-Zip and delete `META-INF/services/javax.annotation.processing.Processor`
