### ISSUE TITLE
`SugarApplicationException`s aren't passed to `IMixinErrorHandler`

### ISSUE THREAD

**Issue by melontini** [LlamaLad7/MixinExtras#46]
While testing `IMixinErrorHandler` on Connector, I noticed that Sugar exceptions aren't passed to the handler.

The Mixin in question: [[link]](https://github.com/melontini/andromeda/blob/1.20-fabric/src/main/java/me/melontini/andromeda/mixin/items/infinite_totem/LivingEntityMixin.java)

The IMixinErrorHandler in question: [[link]](https://github.com/melontini/andromeda/blob/1.20-fabric/src/main/java/me/melontini/andromeda/util/mixin/ErrorHandler.java)

**Comment by LlamaLad7** [comment]
`IMixinErrorHandler` is very broken generally, e.g. no injection check failures get passed to it. Do you have a particular need for sugar exceptions to be passed to it exclusively? If the underlying behaviour in mixin were improved you would be able to get them by looking at the suppressed exceptions from the injection check failure.

**Comment by melontini** [comment]
Ah, wasn't aware of issues with the handler, thank you. (I guess this is what https://github.com/SpongePowered/Mixin/pull/640 is about?)

Anyway, there's no particular need for sugar exceptions. I just assumed this was something to do with sugar exclusively. Sorry.

I'll close this, as this is not an issue with MixinExtras.

**Comment by LlamaLad7** [comment]
Yeah, that getting merged would be ideal.
