### ISSUE TITLE
JitPack build for 0.2.0-rc.5 failed

### ISSUE THREAD

**Issue by MerchantPug** [LlamaLad7/MixinExtras#48]
I'm just saying it here to alert you that this is the case.

**Comment by MerchantPug** [comment]
It's probably not that important of a fix because rc.4 isn't one of the problematic versions but it's a bit annoying nonetheless.

**Comment by Gamebuster19901-Alt** [comment]
I believe this library is on maven central now so you can just use that maven repo. 

However you shouldn’t ever use jitpack. You never know if their build system is up. Additionally, you can’t be 100% sure that jitpack isn’t  providing you a malicious file in place of your dep, you just have to trust that jitpack won’t send you one. If a dep you need isn’t in a maven repository you should be using gradle source dependencies.

**Comment by MerchantPug** [comment]
thanks for telling me about this, I didn't know it was on maven central.

**Comment by LlamaLad7** [comment]
It's been passed for a good while anyway, I re-ran it
