### ISSUE TITLE
[Request] Ability to modify the receiver of instance method calls

### ISSUE THREAD

**Issue by BasiqueEvangelist** [LlamaLad7/MixinExtras#5]
This would allow getting/modifying `this` without using a non-compatible @‌Redirect or a brittle local-capturing @‌Inject

**Comment by LlamaLad7** [comment]
Just to check, you mean receiver before the `.` of a given call, rather than the actual `this` in the current scope, right?

**Comment by BasiqueEvangelist** [comment]
Yeah.

**Comment by LlamaLad7** [comment]
Added in 0.0.3.
