### ISSUE TITLE
Weird Crashing issue that occurs between 1 and 3 minutes after loading singleplayer world.

### ISSUE THREAD

**Issue by cranberriez** [LlamaLad7/MixinExtras#50]
I am still actively trying to debug this issue but here is my latest.log.

[latest.log](https://github.com/LlamaLad7/MixinExtras/files/12836757/latest.log)

The exact issue I am having is here.

`com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 2 but got 1. Expected types were [net.minecraft.world.entity.EntityType, net.minecraft.world.level.Level], actual types were [net.minecraft.server.level.ServerLevel].`

I'm not directly adding mixin extras but it seems to be being added by geckoLib.

Googling has resulted in absolutely no helpful answers, I am actively combing through my mods trying to figure out what combination causes this.

Forge 43.3.2
Minecraft 1.19.2

Neither mod is directly added:
MixinExtras-0.2.0-rc.4.jar
mixinextras-forge-0.2.0-rc.4.jar

**Comment by LlamaLad7** [comment]
Seem to remember this is caused by the midnight mod. It's not an issue with MixinExtras they just bafflingly never tested their code. See if there's an update and if not open an issue on their gitlab.

**Comment by cranberriez** [comment]
AHH THANK YOU
