### ISSUE TITLE
[Question] Why does MixinExtras 0.2.0 for fabric platform requires fabric loader `>=0.14.11`

### ISSUE THREAD

**Issue by Fallen-Breath** [LlamaLad7/MixinExtras#52]
MixinExtras declares dependency on fabric loader `>=0.14.11`, but I don't see any actual code dependency on fabric loader `>=0.14.11` 

https://github.com/LlamaLad7/MixinExtras/blob/b26d42127aee5eca65204238a0a729b0f022cd65/platform/fabric/src/main/resources/fabric.mod.json#L19-L21

The reason why I can't just update my fabric loader is, I have some fabric client setups in mc1.15 and below, that cannot work with fabric loader `>=0.12.0`. I'm also maintaining some mods for those mc versions. If MixinExtras requires fabric loader `>=0.14.11`, then I cannot use MixinExtras 0.2.0 for my mods while still support those client setups

If it's not necessary, I'll suggest to remove this dependency, just like the MixinExtras 0.1.1 that depends on nothing

**Comment by LlamaLad7** [comment]
It requires [this fix](https://github.com/FabricMC/fabric-loader/pull/733). The latest version of fabric loader should work on every mc version, what specific issues are you encountering?

**Comment by LlamaLad7** [comment]
Also you don't have to use the fabric specific artifact, you can still shade and relocate it as explained in the "other platforms" section.

**Comment by Fallen-Breath** [comment]
> The latest version of fabric loader should work on every mc version

the fabric loader itself works, but some mods don't

**Comment by Fallen-Breath** [comment]
> Also you don't have to use the fabric specific artifact, you can still shade and relocate it as explained in the "other platforms" section.

I thought I have to follow the fabric guide in the readme xd

Can I simply apply loom's `include` on `mixinextras-common` and invoke `MixinExtrasBootstrap.init()` in my onw, just like what we do for MixinExtras 0.1.1? cuz using `include` much easier than using `shadow`

**Comment by LlamaLad7** [comment]
No, you cannot. The generated modid will be wrong.

**Comment by LlamaLad7** [comment]
Using mixinextras on <0.14.11 without shading it is kind of not a supported use case at all since you can't initialize it from a mixin plugin without triggering the crash, and if you do it from preLaunch then mixin inheritance won't work properly with its injectors. I sort of assumed everyone would be off those versions by now.

**Comment by LlamaLad7** [comment]
Yes.
