### ISSUE TITLE
Issue with Bad local variable type with another mod's WrapOperation LocalRef

### ISSUE THREAD

**Issue by MerchantPug** [LlamaLad7/MixinExtras#55]
I'm unsure what's going on here, but I seem to be running into this inside the dev environment. This works fine in production.

It could be my setup with a don't remap fabric loom (common) and a fabric loom (fabric specific), but I'm quite lost.

Project:
https://github.com/MerchantPug/apugli/tree/1.20.2

Crashlog:
https://gist.github.com/MerchantPug/2d06a544c8dd0c699a0a18d4739fce87

**Comment by MerchantPug** [comment]
I'll link my repo when I'm done with a few things.

**Comment by MerchantPug** [comment]
https://github.com/MerchantPug/apugli/tree/1.20.2

**Comment by LlamaLad7** [comment]
This is caused by having `-Dmixin.debug.verify=true` on. You should never really set `mixin.debug` globally, instead set the specific options you want like `verbose` and `export`. I will fix the issue at some point but `verify` is broken in many other ways so it's not an urgent priority.

**Comment by MerchantPug** [comment]
> This is caused by having `-Dmixin.debug.verify=true` on. You should never really set `mixin.debug` globally, instead set the specific options you want like `verbose` and `export`. I will fix the issue at some point but `verify` is broken in many other ways so it's not an urgent priority.

Thanks. 👍

**Comment by LlamaLad7** [comment]
Fixed in 0.2.1
