### ISSUE TITLE
Is it possible to do @WrapOperation with @At("HEAD")?

### ISSUE THREAD

**Issue by StewStrong** [LlamaLad7/MixinExtras#60]
I can't seem to get it working. If not, this would be very useful!

**Comment by LlamaLad7** [comment]
Wrapping the first instruction in a method most likely does not make sense depending on what the instruction is. It’s certainly not a stable idea to target. If you want to wrap the entire method then that’d be different and might potentially be planned, i’ll have to see. If you have a specific scenario then just ask in the discord cause it’s probably possible right now anyway.

**Comment by StewStrong** [comment]
Can you link the discord? I can't find it.

**Comment by LlamaLad7** [comment]
Whatever discord your modloader uses, or the sponge powered discord if none of those fit.

**Comment by StewStrong** [comment]
> If you want to wrap the entire method then that’d be different and might potentially be planned
Yeah thats what I want.

Currently I have to do something like this
```java
boolean isModifyingPathType = false;

@Inject(method = "getBlockPathTypeRaw", at = @At("RETURN"), cancellable = true)
private static void getBlockPathTypeForShips(final BlockGetter blockGetter, final BlockPos blockPos,
    final CallbackInfoReturnable<BlockPathTypes> cir) {
    if (isModifyingPathType) {
        return;
    }

    isModifyingPathType = true;

    // Reinvoke with different args
    modified = getBlockPathTypeRaw(((PathNavigationRegionAccessor) blockGetter).getLevel(), groundPos);

    isModifyingPathType = false;
```

It'd be better to write this using something like @WrapMethod.

**Comment by LlamaLad7** [comment]
Well no, you should just use a `ModifyVariable` at `HEAD`. If you want to modify multiple parameters at once then use mutable `Local`s.
