### ISSUE TITLE
Crashing with Connector, I'm assuming its when both a fabric & forge mod integrate this at the same time.

### ISSUE THREAD

**Issue by SlayDigger** [LlamaLad7/MixinExtras#61]
Here is the log, the game is crashing on startup. [](https://gist.github.com/SlayDigger/c83953db9acdf040078c2c979721cc23)

**Comment by SlayDigger** [comment]
Ok funky github formatting didnt work with link, here we go: [https://gist.github.com/SlayDigger/c83953db9acdf040078c2c979721cc23](https://gist.github.com/SlayDigger/c83953db9acdf040078c2c979721cc23)

**Comment by LlamaLad7** [comment]
The log contains no errors.

**Comment by SlayDigger** [comment]
On line 445, the game crashes not long into startup
