### ISSUE TITLE
Using LocalRef throws ClassNotFoundException.

### ISSUE THREAD

**Issue by Garouelcazador** [LlamaLad7/MixinExtras#62]
Hi.

For some reason when I use the LocalRef<> class when using the .jar file of the mod I get java.lang.ClassNotFoundException and apparently it is solved by deleting the methods that use said class

The class that produces the exception:
https://github.com/Garouelcazador/minecraft-1.20.1-shadows_from_the_past-1.0/blob/master/src/main/java/com/garouelcazador/shadows_from_the_past/mixins/ThornsEnchantmentMixin.java

The log:
https://github.com/Garouelcazador/minecraft-1.20.1-shadows_from_the_past-1.0/blob/master/logs/latest.log

The error does not occur when I run the game in my IDE and it does not produce a crash report

I use Google Translate in case English is bad ;w;

**Comment by Earthcomputer** [comment]
The log gives a 404 for me

**Comment by LlamaLad7** [comment]
I was invited to the repo for whatever reason

**Comment by LlamaLad7** [comment]
You are using the wrong jar of your mod. You need to use the one with `-all` at the end because the default one will not include Jar-in-Jar'ed dependencies. Please re-open if that does not fix the issue.

**Comment by Garouelcazador** [comment]
It works thanks!
