### ISSUE TITLE
Returns null value and crashes minecraft every time

### ISSUE THREAD

**Issue by Wulgryn** [LlamaLad7/MixinExtras#67]
Version: Fabric 1.20.1

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.llamalad7.mixinextras.sugar.ref.LocalRef.get()" is null

## Reproduction:

Swim in water, than open inventory. Than it crashes.

## Mods
- alloy-forgery-2.1.2+1.20.jar
- AmbientSounds_FABRIC_v5.3.5_mc1.20.1.jar
- animal_feeding_trough-1.0.3+1.20.1.jar
- appleskin-fabric-mc1.20.1-2.5.1.jar
- architectury-9.1.12-fabric.jar
- badpackets-fabric-0.4.3.jar
- bellsandwhistles-0.4.5+1.20.1-FABRIC.jar
- BetterCookedAxolotls-1.0-1.20.1-Fabric.jar
- cloth-config-11.1.118-fabric.jar
- collective-1.20.1-7.30.jar
- cookedcarrots-1.20.1-0-fabric.jar
- crawl-0.12.0.jar
- create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
- create-structures-0.1.1-1.20.1-FABRIC.jar
- createaddition-fabric+1.20.1-0.9.0.jar
- creatediselgenerators-2.1.3.jar
- createunlimited-0.5.0+mc1.20.1.jar
- Create_Cooking_0.5.jar
- create_enchantment_industry-1.2.12.jar
- create_interactive-1201-fabric-1.0.2-beta.1.jar
- create_trimmed.jar
- CreativeCore_FABRIC_v2.11.16_mc1.20.1.jar
- deeper-oceans-mc1.20-v1.0.1a.jar
- do-a-barrel-roll-3.3.7+1.20-fabric.jar
- eating-animation-1.20+1.9.5.jar
- emi-1.1.0+1.20.1+fabric.jar
- emiffect-fabric-1.1.2+mc1.20.1.jar
- emitrades-fabric-1.2.1+mc1.20.1.jar
- emi_enchanting-0.1.0+1.20.1.jar
- emi_loot-0.6.5+1.20.1.jar
- enchanted-vertical-slabs-1.9.1.jar
- EquipmentCompare-1.20.1-fabric-1.3.7.jar
- eureka-1201-1.3.0-beta.4.jar
- experienceprogress-1.1.0+1.20.jar
- extendedgears-2.1.0-1.20.1-0.5.1.c-fabric.jar
- extra-mod-integrations-0.4.2+1.20.1.jar
- fabric-api-0.88.1+1.20.1.jar
- fallingleaves-1.15.4+1.20.1.jar
- fast-doll-1.1.jar
- flowermimics-1.20.1-1.7.jar
- foodeffecttooltips-1.1.1-1.20.0.jar
- foodtxf-1.20.1-1.5.4-fabric.jar
- ForbiddenPotions-1.1.0-1.20.x.jar
- ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
- fusion-1.1.0c-fabric-mc1.20.1.jar
- gardeners-dream-1.jar
- garnished-1.5.1-hotfix-1+1.20.1.jar
- grabbymobs-1.20.1-1.5.jar
- horde-nights-0.3.1.jar
- Iceberg-1.20.1-fabric-1.1.11.jar
- improvedmobs-1.20.1-1.11.6-fabric.jar
- indium-1.0.21+mc1.20.1.jar
- invisibleframes-1.1.0+1.20.jar
- iris-mc1.20-1.6.4.jar
- LegendaryTooltips-1.20.1-fabric-1.4.4.jar
- lithium-fabric-mc1.20.1-0.11.2.jar
- lititup-1.20.1-4.2.jar
- mod-loading-screen-1.0.4.jar
- modmenu-7.2.2.jar
- moremobvariants-fabric+1.20-1.2.2.jar
- more_mobs-v1.5.1-mc1.14x-1.20x-mod.jar
- notenoughanimations-fabric-1.7.0-mc1.20.1.jar
- notenoughcrashes-4.4.61.20.1-fabric.jar
- owo-lib-0.11.2+1.20.jar
- Pehkui-3.7.12+1.14.4-1.20.4.jar
- PizzaCraft-1.20.1-7.0.7.jar
- Potion-Blender-1.20.1-FABRIC--1.1.0.jar
- potioncauldron-1.0.0-beta.2+mc1.20.jar
- PresenceFootsteps-1.9.1.jar
- Prism-1.20.1-fabric-1.0.5.jar
- progression-reborn-1.20-v1.3.8.jar
- realisticsleep-1.9.1mc1.20.x.jar
- rechiseled-1.1.5b-fabric-mc1.20.jar
- rechiseledcreate-1.0.1-fabric-mc1.20.jar
- redstone-bits-1.10.2+fabric-mc1.20.jar
- reinforced-barrels-2.4.1+1.20.jar
- reinforced-chests-2.4.2+1.20.jar
- skinlayers3d-fabric-1.6.2-mc1.20.1.jar
- sodium-fabric-mc1.20-0.4.10+build.27.jar
- sound-physics-remastered-fabric-1.20.1-1.3.1.jar
- Steam_Rails-1.5.1+fabric-mc1.20.1.jar
- supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
- supermartijn642corelib-1.1.16-fabric-mc1.20.1.jar
- tectonic-mod-1.19.3-v2.2.jar
- tenshilib-1.20.1-1.7.2-fabric.jar
- time-and-wind-ct-1.4.8+1.20-1.20.1.jar
- TimeStackerFabric-1.1.3-1.20.1.jar
- upgraded-mobs-1.3.1.jar
- usageticker-1.0.1-1.20.jar
- UsefulSlime-fabric-1.20.2-1.7.1.jar
- valkyrienskies-120-2.1.3-beta.1.jar
- wthit-fabric-8.4.3.jar
- XaerosWorldMap_1.37.2_Fabric_1.20.jar
- yet-another-config-lib-fabric-3.2.1+1.20.jar
- Zoomify-2.11.1.jar

**Comment by Geolykt** [comment]
You might want to attach a bit more information than that. (especially reproduction steps)

**Comment by LlamaLad7** [comment]
I'm assuming you're on fabric-loader 0.15.4, in which case update. If not please re-open with more info.

**Comment by Wulgryn** [comment]
Thanks, it works now!
