### ISSUE TITLE
Random mixin crashes after adding MixinExtras

### ISSUE THREAD

**Issue by hlysine** [LlamaLad7/MixinExtras#68]
I've recently bundled MixinExtras 0.3.3 in my mod Create: Connected. Since then, I've received multiple crash reports caused by random mixin errors thrown by other mods. I can only assume they are related to MixinExtras because previous versions of C:Connected work fine. Other than the snippet provided in readme, are there other things I need to setup to build and publish mods with MixinExtras?

C:Connected is on Forge 1.18.2/1.19.2/1.20.1
Here's the build script:
https://github.com/hlysine/create_connected/blob/main/build.gradle

Thanks for the help!

**Comment by LlamaLad7** [comment]
0.3.3 causes issues with some setups as now mentioned in its release notes. Please update to 0.3.5 and reopen with logs if the issues continue.
