### ISSUE TITLE
How to build the mod?

### ISSUE THREAD

**Issue by somykOS** [LlamaLad7/MixinExtras#69]
I just wanted to update the Dynamic FPS mod, but it started requiring MixinExtras after that. Now that I've found you, I've also searched your wiki a bit on how to build the mod, because I'm just a player and not a mod coder and don't understand how to do it. But I didn't find it. Please tell me step by step how to do it. I want to build a mod for Fabric 1.20.1

**Comment by LlamaLad7** [comment]
MixinExtras does not change anything about the build process. I suggest you ask in the fabric discord.
