### ISSUE TITLE
Unable to find matching local

### ISSUE THREAD

**Issue by mathisHeidrich** [LlamaLad7/MixinExtras#71]
I can't figure out how to capture the local variables.

[ExampleMixin.java.txt](https://github.com/LlamaLad7/MixinExtras/files/14057861/ExampleMixin.java.txt)
[crash-2024-01-25_22.09.16-server.txt](https://github.com/LlamaLad7/MixinExtras/files/14057834/crash-2024-01-25_22.09.16-server.txt)

I appreciate your help!

**Comment by LlamaLad7** [comment]
You can use `@Local(print = true)` to print the locals. For any further questions about specific scenarios i suggest asking in the relevant discord servers.
