### ISSUE TITLE
Connector

### ISSUE THREAD

**Issue by Krimatoria** [LlamaLad7/MixinExtras#73]
Connector-1.0.0-beta.37+1.20.1.jar
[21:22:51] [main/ERROR] [de.su.si.co.se.FabricMixinBootstrap/]: Non-unique Mixin config name mixinextras.init.mixins.json used by the mods com_github_llamalad7_mixinextras and mixinextras

**Comment by LlamaLad7** [comment]
That’s an issue with connector. They don’t seem to correctly handle aliased modids. Please report to them.

**Comment by Krimatoria** [comment]
> correctly

Ok)))

**Comment by Krimatoria** [comment]
> That’s an issue with connector. They don’t seem to correctly handle aliased modids. Please report to them.

Everything seems to be normal)
https://github.com/Sinytra/Connector/issues/876#issuecomment-1974928178
