### ISSUE TITLE
WrapWithCondition v2 issue

### ISSUE THREAD

**Issue by Skidamek** [LlamaLad7/MixinExtras#74]
Old deprecated `WrapWithCondition` just merges to target class successfully but the new v2 one, does not. Not sure why.
[My mixin](https://gist.github.com/Skidamek/f050514ba4813610e8f1666a5af3f54c)
Here are images
[Debug class v1 (deprecated)](https://github.com/LlamaLad7/MixinExtras/assets/67871298/4aa14ccf-e993-492a-acc8-3f95ff80b2e0)
[Debug class v2](https://github.com/LlamaLad7/MixinExtras/assets/67871298/6ed429dc-2dff-45bc-9265-a5a41022ca6a)
Zip of debug classes of images above
[DebugClasses.zip](https://github.com/LlamaLad7/MixinExtras/files/14545266/DebugClasses.zip)

Tested with latest fapi on fabric 0.15.7 (mixin extras 0.3.5) as well as on neoforge 1.20.1 with ffapi and added manually mixin extras 0.3.5. Same result on both.

**Comment by LlamaLad7** [comment]
I can't reproduce this. Your mixin applies fine for me. Please publish a reproduction repo.

**Comment by LlamaLad7** [comment]
A log would also be useful.

**Comment by Skidamek** [comment]
Huh strange... i have no idea why it does work now
