### ISSUE TITLE
[Suggestion] `@This` annotation

### ISSUE THREAD

**Issue by dhyces** [LlamaLad7/MixinExtras#80]
Wanted to pick people's minds about this kind of annotation:
```java
@Inject(method = "hurt", at = @At("HEAD"))
private void myMixin(int arg, CallbackInfo ci, @This LivingEntity thiz) {
    if (thiz instanceof Player player) {
        // do something
    } else if (thiz instanceof Shulker shulker) {
        // do something else
    }
}
```
Very simple example, it's just for convenience, makes things a little more straightforward

**Comment by LlamaLad7** [comment]
You already have `this` directly, together with appropriate shadowing, extending of the target's parent or casting.

**Comment by dhyces** [comment]
That was closed quickly :p, but I completely understand
