### ISSUE TITLE
Mixin error 

### ISSUE THREAD

**Issue by starlinetor** [LlamaLad7/MixinExtras#88]
Hi i am trying to run mods on Laby mod. I am getting an error on mixins that said to report it to you. 
https://paste.labymod.net/imiteposutogetovixad

**Comment by Earthcomputer** [comment]
This is not a MixinExtras issue. The problem is that Laby mod is shading MixinExtras which you are not supposed to do.

**Comment by LlamaLad7** [comment]
Shading and relocating is fine and is the only option on many platforms.

**Comment by LlamaLad7** [comment]
Since I am unable to debug labymod (likely intentional), please report to them. It is anyway likely to be an issue with their setup rather than MixinExtras itself.
