### ISSUE TITLE
[BUG] error: package com.llamalad7.mixinextras.injector.wrapoperation does not exist

### ISSUE THREAD

**Issue by FaeWulf** [LlamaLad7/MixinExtras#94]
Enviroment: multiloader 1.20.1 (https://github.com/jaredlll08/MultiLoader-Template/tree/1.20.1)
I add this lib like what README.md said:
```gradle
compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1")) {
        jarJar.ranged(it, "[0.4.1,)")
    }
```

No error when running in dev env.
But will get error when build:
```
error: package com.llamalad7.mixinextras.injector.wrapoperation does not exist
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
                                                       ^
```
![image](https://github.com/user-attachments/assets/a66d5b6d-ba82-4161-861d-f87cb12a351d)

**Comment by LlamaLad7** [comment]
Please provide a git repository so I can reproduce

**Comment by FaeWulf** [comment]
> Please provide a git repository so I can reproduce

You can use this https://github.com/FaeWulf/Diversity/tree/1.20.1

**Comment by LlamaLad7** [comment]
The issue is due to mixinextras not being present on your test classpath. You can either add mixinextras to `testCompileOnly` as well as `compileOnly`, or you can add it to `implementation` instead.
