### ISSUE TITLE
Manual call to init() is required for Forge 1.18.2 under Architectury Loom

### ISSUE THREAD

**Issue by cosmicdan** [LlamaLad7/MixinExtras#99]
Heya,

This might only be an issue when using a MixinPlugin, but I found that none of the MixinExtras hooks would work (they'd simply not apply) unless I manually called `MixinExtrasBootstrap.init();` as explained under the "Any other platform" part of the readme.

Occurs in Architectury Loom for 1.18.2, however in 1.20.1 there was no such problem. All other build config is the same. Haven't tested any versions in-between those, though.

Mostly just reporting as a heads up for other users, it's not a big deal. Cheers!

**Comment by LlamaLad7** [comment]
Make sure you are on a new enough version of forge since jarjar is broken on many 1.18.2 versions. Reopen with a reproduction case if it still doesn't work on the latest forge.
